(function() {var implementors = {};
implementors["db"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"db/kv/struct.CompactionProfile.html\" title=\"struct db::kv::CompactionProfile\">CompactionProfile</a>",synthetic:false,types:["db::kv::diskdb::CompactionProfile"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"db/kv/enum.Location.html\" title=\"enum db::kv::Location\">Location</a>",synthetic:false,types:["db::kv::transaction::Location"]},];
implementors["keys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"keys/enum.Type.html\" title=\"enum keys::Type\">Type</a>",synthetic:false,types:["keys::address::Type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"keys/enum.Network.html\" title=\"enum keys::Network\">Network</a>",synthetic:false,types:["keys::network::Network"]},];
implementors["message"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/common/enum.InventoryType.html\" title=\"enum message::common::InventoryType\">InventoryType</a>",synthetic:false,types:["message::common::inventory::InventoryType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/common/struct.IpAddress.html\" title=\"struct message::common::IpAddress\">IpAddress</a>",synthetic:false,types:["message::common::ip::IpAddress"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/common/struct.Port.html\" title=\"struct message::common::Port\">Port</a>",synthetic:false,types:["message::common::port::Port"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"message/struct.Services.html\" title=\"struct message::Services\">Services</a>",synthetic:false,types:["message::common::service::Services"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/types/enum.FilterFlags.html\" title=\"enum message::types::FilterFlags\">FilterFlags</a>",synthetic:false,types:["message::types::filterload::FilterFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"message/types/reject/enum.RejectCode.html\" title=\"enum message::types::reject::RejectCode\">RejectCode</a>",synthetic:false,types:["message::types::reject::RejectCode"]},];
implementors["miner"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"miner/enum.MemoryPoolOrderingStrategy.html\" title=\"enum miner::MemoryPoolOrderingStrategy\">OrderingStrategy</a>",synthetic:false,types:["miner::memory_pool::OrderingStrategy"]},];
implementors["network"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"network/enum.TransactionOrdering.html\" title=\"enum network::TransactionOrdering\">TransactionOrdering</a>",synthetic:false,types:["network::consensus::TransactionOrdering"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"network/struct.Deployment.html\" title=\"struct network::Deployment\">Deployment</a>",synthetic:false,types:["network::deployments::Deployment"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"network/enum.Network.html\" title=\"enum network::Network\">Network</a>",synthetic:false,types:["network::network::Network"]},];
implementors["p2p"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"p2p/enum.InternetProtocol.html\" title=\"enum p2p::InternetProtocol\">InternetProtocol</a>",synthetic:false,types:["p2p::util::internet_protocol::InternetProtocol"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"p2p/enum.Direction.html\" title=\"enum p2p::Direction\">Direction</a>",synthetic:false,types:["p2p::util::peer::Direction"]},];
implementors["primitives"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"primitives/compact/struct.Compact.html\" title=\"struct primitives::compact::Compact\">Compact</a>",synthetic:false,types:["primitives::compact::Compact"]},];
implementors["rpc"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rpc/v1/types/enum.BlockTemplateRequestMode.html\" title=\"enum rpc::v1::types::BlockTemplateRequestMode\">BlockTemplateRequestMode</a>",synthetic:false,types:["rpc::v1::types::block_template_request::BlockTemplateRequestMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rpc/v1/types/struct.U256.html\" title=\"struct rpc::v1::types::U256\">U256</a>",synthetic:false,types:["rpc::v1::types::uint::U256"]},];
implementors["script"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"script/struct.Num.html\" title=\"struct script::Num\">Num</a>",synthetic:false,types:["script::num::Num"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"script/enum.Opcode.html\" title=\"enum script::Opcode\">Opcode</a>",synthetic:false,types:["script::opcode::Opcode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"script/enum.SignatureVersion.html\" title=\"enum script::SignatureVersion\">SignatureVersion</a>",synthetic:false,types:["script::sign::SignatureVersion"]},];
implementors["serialization"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"serialization/struct.CompactInteger.html\" title=\"struct serialization::CompactInteger\">CompactInteger</a>",synthetic:false,types:["serialization::compact_integer::CompactInteger"]},];
implementors["verification"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonBlock.html\" title=\"struct verification::CanonBlock\">CanonBlock</a>&lt;'a&gt;",synthetic:false,types:["verification::canon::CanonBlock"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonHeader.html\" title=\"struct verification::CanonHeader\">CanonHeader</a>&lt;'a&gt;",synthetic:false,types:["verification::canon::CanonHeader"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"verification/struct.CanonTransaction.html\" title=\"struct verification::CanonTransaction\">CanonTransaction</a>&lt;'a&gt;",synthetic:false,types:["verification::canon::CanonTransaction"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"verification/enum.VerificationLevel.html\" title=\"enum verification::VerificationLevel\">VerificationLevel</a>",synthetic:false,types:["verification::VerificationLevel"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
